### ISSUE TITLE
Errors while trying to run test-main.tcl

### ISSUE THREAD

**Issue by ehlyzov** [ivannp/deal.lib#1]
I tried to get myself comfortable with the Deal and found your awesome library. But it looks like some definitions are missing:
```
deal -i ./lib.ivannp/test-main.tcl
```
results into:
```
Tcl stack dump of error info:
invalid command name "clear_comments"
    while executing
"clear_comments"
    invoked from within
"deal_loop write_deal"
```
Could you please advise how to handle over it?

**Comment by ivannp** [comment]
I managed to find the [supporting file](https://gist.github.com/ivannp/2ee69f87d36574c77a7e1e75033cc974). Use my file **to add** what's missing to format/default, **don't copy it** directly - depends what version of deal you are using (mine is 3.19).

**Comment by ehlyzov** [comment]
Thank you! I've managed to merge the files and now it works as supposed.
